name: metadocker
dependencies:
  - python
text: |
  ## This installs everything needed to build docker images

  # Install needed system packages for Docker
  RUN sudo apt-get install -y \
      apt-transport-https \
      ca-certificates \
      gnupg-agent \
      software-properties-common

  # Add Docker's official GPG key
  RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

  # Set up the stable version of the Docker repo
  RUN sudo add-apt-repository \
     "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
     $(lsb_release -cs) \
     stable"
  RUN sudo apt-get update

  # Install the latest Docker version of Community Edition
  RUN sudo apt-get install -y docker-ce docker-ce-cli containerd.io
