name: metadocker
dependencies:
  - python
text: |
  ## This installs everything needed to build docker images

  # Install needed system packages for Docker
  APTGET apt-transport-https
  APTGET ca-certificates
  APTGET gnupg-agent
  APTGET software-properties-common

  # Add Docker's official GPG key
  RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

  # Set up the stable version of the Docker repo
  RUN sudo add-apt-repository \
     "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
     $(lsb_release -cs) stable"
  RUN sudo apt-get update

  # Install the latest Docker version of Community Edition
  APTGET docker-ce
  APTGET docker-ce-cli
  APTGET containerd.io

  # Get the credential helper for Docker+GoogleCloudRepo
  RUN curl -fsSL "https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v2.0.0/docker-credential-gcr_linux_amd64-2.0.0.tar.gz" \
    | tar xz --to-stdout ./docker-credential-gcr \
    > /usr/bin/docker-credential-gcr && chmod +x /usr/bin/docker-credential-gcr
  RUN docker-credential-gcr configure-docker
