name: python
location: docker
dependencies: []
text: |
  ## This installs a working python 3 environment
  
  # Some programs will need legacy python
  APTGET python-pip
  APTGET python-dev

  # Python 3 packages\n
  APTGET python3
  APTGET python3-dev
  APTGET python3-pip
  APTGET python3-setuptools
  PIP3 wheel
  PIP3 pyyaml
