uid: jupyterlab
location: docker
dependencies:
  - python
  # NOTE add this back in after ubuntu 20.04 release 
  # - nodejs
text: |
  ## This installs jupyterlab, which will set up a server
  PIP jupyterlab

  # Install Tini, a requirement to stably run a docker container with a jupyter server
  # Optionally, docker can be run with the --init arg (newer docker ver. contains tini)
  ADD https://github.com/krallin/tini/releases/download/v0.18.0/tini /usr/bin/tini
  RUN chmod +x /usr/bin/tini
  ENTRYPOINT ["/usr/bin/tini", "--"]

  PIP jupytext
  RUN jupyter nbextension install --py jupytext
  RUN jupyter nbextension enable --py jupytext

  ENV PYSPARK_PYTHON "/usr/bin/python3"
