uid: metadocker
location: docker
dependencies: []
text: |
  ## This installs everything needed to build docker images
  # Install needed system packages for Docker
  APT apt-transport-https ca-certificates gnupg-agent software-properties-common

  # Add Docker's official GPG key and repository
  RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  RUN sudo add-apt-repository \
     "deb [arch=amd64] https://download.docker.com/linux/ubuntu eoan stable"
   # "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   # $(lsb_release -cs) stable"

  # Install the latest Docker version of Community Edition
  APT docker-ce docker-ce-cli containerd.io

  # Get the credential helper for Docker+GoogleCloudRepo
  RUN curl -fsSL "https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v2.0.0/docker-credential-gcr_linux_amd64-2.0.0.tar.gz" \
    | tar xz --to-stdout ./docker-credential-gcr \
    > /usr/bin/docker-credential-gcr && chmod +x /usr/bin/docker-credential-gcr
  RUN docker-credential-gcr configure-docker
